### Get a key
GET http://localhost:9098/stoo-kv/my-app/prod/database.password

### Get All keys
GET http://localhost:9098/stoo-kv

### Get Keys by namespace & profile
GET http://localhost:9098/stoo-kv/my-app/prod

### Set key
POST  http://localhost:9098/stoo-kv/my-app/prod?database.password={ENC} 17673de9aaf47b0dd3a83d23eddaef5c0184ce5e95e9b31673d5b83cdcb17d4b807da35a

### Set secret key
POST  http://localhost:9098/stoo-kv/secrets/my-app/prod?database.password=123456aaa*

### Set plain key
POST  http://localhost:9098/stoo-kv/my-app/prod?database.username2=root3

### Delete key

DELETE  http://localhost:9098/stoo-kv/my-app/prod?key=database.password

### Encrypt Data
POST  http://localhost:9098/stoo-kv/encrypt
Content-Type: text/plain

123456a*

### Decrypt Data
POST  http://localhost:9098/stoo-kv/decrypt
Content-Type: text/plain

48fa702f0614a5550a4ebf98e2541e8708afe23bce365d14c100d1b7d1c455534e433ed32867ffdfdf